### ISSUE TITLE
compiling error for variable long long dt = {500, 500};

### ISSUE THREAD

**Issue by ibexnet** [DaniFoldi/Async_Operations#1]
Sorry if the question is stupid but I'm new to c.
When I put the following code:
long long dt = {500, 500};
Async_Operations blinker(&dt, 2, -1, LED_BUILTIN);

I have an error during compilation:
error: scalar object 'dt' requires one element in initializer
 long long dt = {500, 500};
           ^~~~

**Comment by DaniFoldi** [comment]
Hi! It's been quite some time since I wrote this library (or used an Arduino), I will give it a go tomorrow. Please bump the issue if I don't respond by the weekend.

Cheers,
Dani

**Comment by DaniFoldi** [comment]
It looks like it was early morning when I wrote the examples.
Solution: declare `dt` as an array, and no need for passing `&dt` to the constructor. Please try
```c
long long dt[] = {500, 500};
Async_Operations blinker(dt, 2, -1, LED_BUILTIN);
```

**Comment by DaniFoldi** [comment]
Please reopen if this doesn't fix the issue.

**Comment by the-moog** [comment]
The confusion comes from the fact that the API declaration of the steps argument in the constructor is incorrect, at least IMO.

i.e.
Async_Operations(long long *steps, ....

"long long * steps" means "steps is a pointer to a long long"

whereas
long long steps[] = {1,2,3,4};

means steps is a pointer to an *array* of long longs.

Taking the address of the array is usually considered not the same (or at best not very portable) as taking the address of the first entry in that array.  i.e. &data  is not always the same as &data[0], depending on how the CPU architecture works.
Most compilers have no way to differentate between base of array and address of first item in the array.  Dependent on endianness and/or use of casts then that address might not be the same.

I.e. There is an implied assumption that the array is contiguous in memory and that all we know is the address of the first item, and promice to play nicely with the size. We don't know how large it is though we can use sizeof() to find that at compile time.
BTW this causes all sorts of issues where the apparent vs phsical size of the array items is not consistant across platforms or compilers.

In any case, this is C++ so data should be a proper type, no need to separately pass the size or know where it lives.
i.e.
Async_Operations(std::vector<long long> steps, ....

You can pass a reference to an array (not ideal btw as it meabs steps[1] = {100} will not work, but steps[] = {100} will.
Async_Operations(long long steps[] &, ....  but you will still need to work out the size = sizeof(array)/sizeof(long long)
And for non-fixed array sizes this is no different to passing a pointer.

I must point out there is no need for several implementations and overloaded constructors, all cut and paste as you have now. Just use default arguments in the prototypes, e.g.
```
    Async_Operations(std::vector<long long>steps &, int repeat=1, int pin=-1, bool initialState=true, bool endState=false);
    Async_Operations(long long steps[], int stepCount, int repeat=1, int pin=-1, bool initialState=true, bool endState=false);
    Async_Operations(long long * steps, int stepCount, int repeat=1, int pin=-1, bool initialState=true, bool endState=false);
```

Now instead of using overloading to deal with variant types (which you could use templated functions for anyway) you could use overloading to deal with different use cases, like this:

```
    Async_Operations(std::vector<long long>steps &, int repeat=1, int pin=-1, bool initialState=true, bool endState=false);
    Async_Operations(long long period, int repeat=1, int pin=-1, bool initialState=true, bool endState=false);

// Here for backwards compatability
  Async_Operations::Async_Operations(long long * periods_p, unsigned stepCount, int repeat=1, int pin=-1, bool initialState=true, bool endState=false);
```

I've made those changes and will submit a pull req once I update your examples.
